before_install:
  - sudo apt-get install -y libapr1-dev libboost-atomic-dev libboost-system-dev
language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
